### ISSUE TITLE
Strange JSONDecodeError

### ISSUE THREAD

**Issue by Rocketboy235** [everettsouthwick/trusted-traveler-scheduler#26]
**Describe the bug**
Trying to run after setting up the config.json and installing all of the packages called out in the requirements.txt
Experienced the following traceback in the screenshot below

**Screenshots**
![image](https://github.com/everettsouthwick/trusted-traveler-scheduler/assets/29405055/c4860b8f-c338-472a-a2ca-15c4b809d070)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Python v3.10.11

**Comment by everettsouthwick** [comment]
Hello, could you share your config please? Block out any tokens in the "notification_urls" configuration option if you have them.

**Comment by Rocketboy235** [comment]
Hi, sure thing.

![image](https://github.com/everettsouthwick/trusted-traveler-scheduler/assets/29405055/00365876-60cb-4680-8fea-489a49e3c61f)

I currently haven't hooked it up to Discord yet but wondering if I could run this without it for now.

**Comment by everettsouthwick** [comment]
It looks like it is because `0411` in `location_ids` is not a valid integer because of the preceding 0. Are you sure that is a valid location id? You can take a look in  [LOCATIONS.md](https://github.com/everettsouthwick/trusted-traveler-scheduler/blob/eb0d91453fb73f54c643d9c40a86a3e1ac322826/LOCATIONS.md) to see valid locations. 

If `0411` is the location you need, you could try to wrap it in double quotes to make it a string like this:
```json
  "location_ids": [ "0411" ],
  ```

**Comment by everettsouthwick** [comment]
I think you might be looking for `14681` - Bradley International Airport Enrollment Center. `0411` is the `locationCode` and it matches on the `id`, not the `locationCode`

**Comment by Rocketboy235** [comment]
Ah I see. After you pointed it out, I forgot about the fact that it's an integer and not a string. Pulled the number from some other list and after looking at your locations.md it's different. Thanks!
